services:
  - type: web
    name: magiuniverso-discordbot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: MTM3Mzk5NjM0MTUyNDY5NzEyMQ.GuYYKL.bLY34vspTLcZ7K2wbq8kF2NP7C1F02m0jrdKcI
        sync: false
